"use client";

import { Sidebar } from "@/features/sidebar";
import { ThemeProvider } from "@/styles";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
        <ThemeProvider>
          <Sidebar />
          {children}
        </ThemeProvider>
      </QueryClientProvider>
    </html>
  );
}
